[workspace]
resolver = "2"
members = [
    "kubizone-crds",
    "kubizone",
    "kubizone-crd-utils"
]

[workspace.dependencies]
kube = { version = "0.85.0", default-features = false }
k8s-openapi = { version = "0.19.0", features = ["v1_25"] }
