---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-corefile
data:
  Corefile: |-
    .:53 {
        errors
        log stdout
        health {
            lameduck 5s
        }
        ready
        {{- range .Values.zonefiles }}
        file /zonefiles/{{ . }}
        {{- end }}
        cache
    }
