---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-corefile
data:
  Corefile: |-
    {{ range .Values.zoneFiles }}
    {{- $zonefile := .zonefile }}
    {{- range .zones }}
    {{ . }} {
        errors
        log stdout
        ready
        file /zonefiles/{{ $zonefile }}/{{ . }}
        cache
    }
    {{- end }}
    {{- end }}
