apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "zonefile-coredns.fullname" . }}
  labels:
    {{- include "zonefile-coredns.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zonefile-coredns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zonefile-coredns.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zonefile-coredns.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "coredns"
          image: "{{ .Values.coredns.image.repository }}:{{ .Values.coredns.image.tag }}"
          imagePullPolicy: {{ .Values.coredns.image.pullPolicy }}
          args: [ "-conf", "/etc/coredns/Corefile" ]
          volumeMounts:
          - name: config-volume
            mountPath: /etc/coredns
          {{- range .Values.zoneFiles }}
          - name: {{ .zonefile }}
            mountPath: zonefiles/{{ .zonefile }}
          {{- end }}
          ports:
            - name: dns
              containerPort: 53
              protocol: UDP
          resources:
            {{- toYaml .Values.coredns.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-corefile
          items:
          - key: Corefile
            path: Corefile
      {{- range .Values.zoneFiles }}
      - name: {{ .zonefile }}
        configMap:
          name: {{ .zonefile }}
          items:
            {{- range .zones }}
            - key: {{ . }}
              path: {{ . }}
            {{- end }}
      {{- end }}
