apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "zonefile-coredns.fullname" . }}
  labels:
    {{- include "zonefile-coredns.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zonefile-coredns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zonefile-coredns.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zonefile-coredns.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "coredns"
          image: "{{ .Values.coredns.image.repository }}:{{ .Values.coredns.image.tag }}"
          imagePullPolicy: {{ .Values.coredns.image.pullPolicy }}
          args: [ "-conf", "/etc/coredns/Corefile" ]
          volumeMounts:
          - name: config-volume
            mountPath: /etc/coredns
          - name: zonefiles
            mountPath: /zonefiles
          ports:
            - name: dns
              containerPort: 53
              protocol: UDP
          resources:
            {{- toYaml .Values.coredns.resources | nindent 12 }}
        - name: "updater"
          image: "{{ .Values.updater.image.repository }}:{{ .Values.updater.image.tag }}"
          imagePullPolicy: {{ .Values.updater.image.pullPolicy }}
          command: ["/scripts/update.sh"]
          args:
            {{- range .Values.zonefiles }}
            - {{ . }}
            {{- end }}
          volumeMounts:
          - name: updater-volume
            mountPath: /scripts/update.sh
            subPath: update.sh
          - name: zonefiles
            mountPath: /zonefiles

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-corefile
          items:
          - key: Corefile
            path: Corefile
      - name: updater-volume
        configMap:
          name: {{ .Release.Name }}-updater
          defaultMode: 0744
      - name: zonefiles
        emptyDir: {}
