{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zonefile-coredns.serviceAccountName" . }}
  labels:
    {{- include "zonefile-coredns.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zonefile-coredns-{{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zonefile-coredns-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ include "zonefile-coredns.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: zonefile-coredns-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
