# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ .Release.Name }}-updater
# data:
#   update.sh: |-
#     #!/usr/bin/env bash
#     echo "Monitoring the following zonefiles: $@"

#     while true; do
#       for zonefile in $@; do
#         configmap=$(kubectl get zonefile $zonefile -o jsonpath='{.status.configMap}')

#         kubectl get configmap $configmap -o jsonpath='{.data.zonefile}' > /zonefiles/$zonefile
#       done

#       sleep 10
#     done
