{{- if .Values.zonefile.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zonefile.fullname" . }}-controller
  labels:
    {{- include "zonefile.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.zonefile.replicaCount }}
  selector:
    matchLabels:
      {{- include "zonefile.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.zonefile.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zonefile.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.zonefile.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zonefile.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.zonefile.podSecurityContext | nindent 8 }}
      {{- if .Values.dangerRecreateCrds }}
      initContainers:
        - name: crds
          securityContext:
            {{- toYaml .Values.zonefile.securityContext | nindent 12 }}
          {{- if .Values.zonefile.image.tag }}
          image: "{{ .Values.zonefile.image.repository }}:{{ .Values.zonefile.image.tag }}"
          {{- else }}
          image: "{{ .Values.zonefile.image.repository }}:v{{ .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.zonefile.image.pullPolicy }}
          resources:
            {{- toYaml .Values.zonefile.resources | nindent 12 }}
          args:
            - danger-recreate-crds
      {{- end }}
      containers:
        - name: controller
          securityContext:
            {{- toYaml .Values.zonefile.securityContext | nindent 12 }}
          {{- if .Values.zonefile.image.tag }}
          image: "{{ .Values.zonefile.image.repository }}:{{ .Values.zonefile.image.tag }}"
          {{- else }}
          image: "{{ .Values.zonefile.image.repository }}:v{{ .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.zonefile.image.pullPolicy }}
          resources:
            {{- toYaml .Values.zonefile.resources | nindent 12 }}
          args:
            {{- toYaml .Values.zonefile.args | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zonefile.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zonefile.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}