{{- if .Values.zonefile.enable }}
{{- if .Values.zonefile.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zonefile.serviceAccountName" . }}
  labels:
    {{- include "zonefile.labels" . | nindent 4 }}
  {{- with .Values.zonefile.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zonefile-{{ .Release.Name }}
rules:
- apiGroups: ["kubi.zone"]
  resources: ["zonefiles", "zonefiles/status"]
  verbs: ["patch", "update", "get", "watch", "list"]
- apiGroups: ["kubi.zone"]
  resources: ["zones", "zones/status"]
  verbs: ["patch", "get", "watch", "list"]
- apiGroups: ["kubi.zone"]
  resources: ["records", "records/status"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "patch", "update", "get", "watch", "list"]
{{- if .Values.dangerRecreateCrds }}
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["patch", "update", "get", "list", "delete", "watch", "create"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zonefile-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ include "zonefile.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: zonefile-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}