# This is an example showcasing selective delegation between zones.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: example-org
spec:
  domainName: example.org.
  delegations:
    - zones: ["*.example.org."]
    - records:
      - pattern: "www.subdomain.example.org."
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: subdomain-example-org
spec:
  domainName: subdomain
  zoneRef:
    name: example-org
  delegations:
    - records:
        - pattern: "ns1.@"
          types: ["A"]
        - pattern: "ns2.@"
          types: ["A"]
        - pattern: "@"
          types: ["NS"]
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-subdomain-example-org
spec:
  domainName: www.subdomain.example.org.
  type: A
  rdata: "192.168.0.2"
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: ns1-subdomain-example-org
spec:
  domainName: ns1.subdomain.example.org.
  type: A
  rdata: "192.168.0.10"
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: ns2-subdomain-example-org
spec:
  domainName: ns2.subdomain.example.org.
  type: A
  rdata: "192.168.0.11"
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: ns-ns1-subdomain-example-org
spec:
  domainName: subdomain.example.org.
  type: NS
  rdata: ns1.subdomain.example.org.
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: ns-ns2-subdomain-example-org
spec:
  domainName: subdomain.example.org.
  type: NS
  rdata: ns2.subdomain.example.org.
