---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: example-org
spec:
  domainName: example.org.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: fqdn-example-org
spec:
  domainName: fqdn.example.org.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: ref-example-org
spec:
  domainName: ref
  zoneRef:
    name: example-org
