---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: example-org
spec:
  name: example.org.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: fqdn-example-org
spec:
  name: fqdn.example.org.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: ref-example-org
spec:
  name: ref
  zoneRef:
    name: example-org
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-ref-example-org
spec:
  name: www.ref.example.org.
  type: A
  rdata: "192.168.0.1"
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-example-org
spec:
  name: www.example.org.
  type: A
  rdata: "192.168.0.2"
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-sub-lol-ref-example-org
spec:
  name: www.sub.lol
  zoneRef:
    name: ref-example-org
  type: A
  rdata: "192.168.0.3"
---