---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: example-org
  namespace: kubizone
spec:
  name: example.org.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: fqdn-example-org
  namespace: kubizone
spec:
  name: fqdn.example.org.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: ref-example-org
  namespace: kubizone
spec:
  name: ref
  zoneRef:
    name: example-org
    namespace: kubizone
